_BASE_: "../Base-BoxInstSemanticStatic.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("beet_bohan_train",)
  TEST: ("beet_bohan_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  MAX_ITER: 20000
  STEPS: (14000, 18000)
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "output/boxinst_semantic_static_beet_bohan_r50_1x"
